apiVersion: v1
kind: ConfigMap
metadata:
  name: neon-compute-spec
  namespace: neon
data:
  spec.json: |
    {
      "format_version": 1.0,
      "cluster": {
          "cluster_id": "neon_test",
          "name": "neon_test",
          "roles": [
              {
                  "name": "cloud_admin",
                  "encrypted_password": "b093c0d3b281ba6da1eacc608620abd8",
                  "options": null
              }
          ],
          "databases": [
          ],
          "settings": [
              {
                  "name": "fsync",
                  "value": "off",
                  "vartype": "bool"
              },
              {
                  "name": "wal_level",
                  "value": "logical",
                  "vartype": "enum"
              },
              {
                  "name": "wal_log_hints",
                  "value": "on",
                  "vartype": "bool"
              },
              {
                  "name": "log_connections",
                  "value": "on",
                  "vartype": "bool"
              },
              {
                  "name": "port",
                  "value": "55433",
                  "vartype": "integer"
              },
              {
                  "name": "shared_buffers",
                  "value": "1MB",
                  "vartype": "string"
              },
              {
                  "name": "max_connections",
                  "value": "100",
                  "vartype": "integer"
              },
              {
                  "name": "listen_addresses",
                  "value": "0.0.0.0",
                  "vartype": "string"
              },
              {
                  "name": "max_wal_senders",
                  "value": "10",
                  "vartype": "integer"
              },
              {
                  "name": "max_replication_slots",
                  "value": "10",
                  "vartype": "integer"
              },
              {
                  "name": "wal_sender_timeout",
                  "value": "5s",
                  "vartype": "string"
              },
              {
                  "name": "wal_keep_size",
                  "value": "0",
                  "vartype": "integer"
              },
              {
                  "name": "password_encryption",
                  "value": "md5",
                  "vartype": "enum"
              },
              {
                  "name": "restart_after_crash",
                  "value": "off",
                  "vartype": "bool"
              },
              {
                  "name": "synchronous_standby_names",
                  "value": "walproposer",
                  "vartype": "string"
              },
              {
                  "name": "shared_preload_libraries",
                  "value": "neon",
                  "vartype": "string"
              },
              {
                  "name": "neon.safekeepers",
                  "value": "safekeeper1:5454,safekeeper2:5454,safekeeper3:5454",
                  "vartype": "string"
              },
              {
                  "name": "neon.timeline_id",
                  "value": "3858f62230ac3c915f300c664312c63f",
                  "vartype": "string"
              },
              {
                  "name": "neon.tenant_id",
                  "value": "c157a79031e1c40f85931829bc5fc552",
                  "vartype": "string"
              },
              {
                  "name": "neon.pageserver_connstring",
                  "value": "host=pageserver port=6400",
                  "vartype": "string"
              },
              {
                  "name": "max_replication_write_lag",
                  "value": "500MB",
                  "vartype": "string"
              },
              {
                  "name": "max_replication_flush_lag",
                  "value": "10GB",
                  "vartype": "string"
              }
          ]
      },

      "delta_operations": [
      ],

      "safekeeper_connstrings": [
        "postgresql://postgres:@10.244.0.86:5454",
        "postgresql://postgres:@10.244.0.85:5454",
        "postgresql://postgres:@10.244.0.84:5454"
      ]
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compute-node
  namespace: neon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compute-node
  template:
    metadata:
      labels:
        app: compute-node
    spec:
      containers:
      - name: storage-broker
        image: localhost:5001/neon-compute-node:latest
        args:
        - "--pgdata"
        - "/.neon/data/pgdata"
        - "--connstr"
        - "postgresql://postgres:@neon-pageserver-0:6400/postgres"
        - "--compute-id"
        - "neon-test"
        - "--spec-path"
        - "/var/spec.json"
        - "--pgbin"
        - "/usr/local/bin/postgres"
        ports:
        - containerPort: 50051
        volumeMounts:
        - name: spec-volume
          mountPath: /var
        - name: pgdata
          mountPath: /.neon/data
      volumes:
      - name: spec-volume
        configMap:
          name: neon-compute-spec
      - name: pgdata
        emptyDir:
          sizeLimit: 500Mi
