apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pageserver
  namespace: neon
spec:
  serviceName: "pageserver"
  replicas: 1
  selector:
    matchLabels:
      app: pageserver
  template:
    metadata:
      labels:
        app: pageserver
    spec:
      containers:
      - name: pageserver
        image: localhost:5001/neon:latest
        command:
        - "/usr/local/bin/pageserver"
        - '-c=listen_pg_addr = "0.0.0.0:6400"'
        - '-c=broker_endpoint = "http://storage-broker-service.neon.svc.cluster.local:50051"'
        volumeMounts:
        - name: pageserver-storage
          mountPath: /data/.neon/tenants  # Adjust the mount path as needed
        ports:
        - containerPort: 6400
        - containerPort: 9898
        env:
        - name: DEFAULT_PG_VERSION
          value: "15"
  volumeClaimTemplates:
  - metadata:
      name: pageserver-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: neon
  name: pageserver
spec:
  clusterIP: None
  selector:
    app: pageserver
  ports:
  - protocol: TCP
    port:  6400
    targetPort: 6400
