---
apiVersion: v1
kind: Namespace
metadata:
  name: neon-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: neon-operator
  namespace: neon-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neon-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - services/finalizers
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - neon.tech
    resources:
      - neonclusters
      - neonclusters/status
      - neonclusters/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neon-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: neon-operator
subjects:
  - kind: ServiceAccount
    name: neon-operator
    namespace: neon-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neon-operator
  namespace: neon-system
  labels:
    app: neon-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neon-operator
  template:
    metadata:
      labels:
        app: neon-operator
    spec:
      serviceAccountName: neon-operator
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: operator
          image: neon-operator:latest # You'll need to update this with your actual image
          imagePullPolicy: IfNotPresent
          command:
            - /neon-operator
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
